name: docker
 
on:
 push:
   branches: [master]
 
jobs:
 registry-cache:
   runs-on: ubuntu-latest
   steps:
     -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
     -
       name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v1
     -
       name: Login to DockerHub
       uses: docker/login-action@v1
       with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
     - uses: actions/checkout@v2
     -
       name: Build and push logproxy-filter-drop
       uses: docker/build-push-action@v2
       with:
         context: ./logproxy-filter-drop
         file: ./logproxy-filter-drop/Dockerfile
         platforms: linux/amd64,linux/arm64
         push: true
         tags: philipssoftware/logproxy-filter-drop:latest
         cache-from: type=registry,ref=philipssoftware/logproxy-filter-drop:latest
         cache-to: type=inline
